server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://cardsdb:3306/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true