server:
  port: 9000
spring:
  application:
    name: cards
  config:
    import: configserver:http://configserver:8071/
  datasource:
    url: jdbc:mysql://cardsdb:3306/cardsdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest



management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

eureka:
  instance:
    preferIpAddress: true
    hostname: cards
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/

info:
  app:
    name: "cards"
    description: "EazyBank Cards Application"
    version: "1.0.0"
