server:
  port: 8090

spring:
  application:
    name: loans
  config:
    import: configserver:http://configserver:8071/
  datasource:
    url: jdbc:mysql://loansdb:3306/loansdb
    username: root
    password: root
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
    hostname: loans
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver:8761/eureka/
    healthcheck:
      enabled: true

info:
  app:
    name: "loans"
    description: "EazyBank Loans Application"
    version: "1.0.0"
