---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:RELEASE.2024-12-18T13-15-44Z
        args:
        - server
        - /data
        ports:
        - containerPort: 9000
        env:
        - name: MINIO_ROOT_USER
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MINIO_ROOT_USER
        - name: MINIO_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MINIO_ROOT_PASSWORD
        - name: MINIO_PROMETHEUS_AUTH_TYPE
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MINIO_PROMETHEUS_AUTH_TYPE
        - name: MINIO_UPDATE
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: MINIO_UPDATE
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 20
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  selector:
    app: minio
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          sleep 10
          mc alias set myminio http://minio:9000 loki supersecret
          mc mb myminio/loki-data --ignore-existing
          mc mb myminio/loki-ruler --ignore-existing
          echo "Buckets created successfully"

