---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.4.0
        args:
        - start-dev
        ports:
        - containerPort: 8080
        env:
        - name: KC_BOOTSTRAP_ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: KC_BOOTSTRAP_ADMIN_USERNAME
        - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eazybank-configmap
              key: KC_BOOTSTRAP_ADMIN_PASSWORD
        volumeMounts:
        - name: keycloak-data
          mountPath: /opt/keycloak/data
      volumes:
      - name: keycloak-data
        persistentVolumeClaim:
          claimName: keycloak-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  type: LoadBalancer
  ports:
    - name: http
      port: 7080
      targetPort: 8080

