apiVersion: v1
kind: ConfigMap
metadata:
  name: eazybank-observability-configmap
data:
  # OpenTelemetry Configuration
  # Apply this ConfigMap ONLY when observability stack (Tempo) is deployed
  JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-2.11.0.jar"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://tempo:4318"
  OTEL_METRICS_EXPORTER: "none"
  OTEL_LOGS_EXPORTER: "none"
  OTEL_SERVICE_NAME: "eazybank-service"

