services:
  accountsdb:
    container_name: accountsdb
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: accountsdb
    extends:
      file: common-config.yml
      service: db-service

  loansdb:
    container_name: loansdb
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: loansdb
    extends:
      file: common-config.yml
      service: db-service

  cardsdb:
    container_name: cardsdb
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: cardsdb
    extends:
      file: common-config.yml
      service: db-service

  rabbitmq:
    image: rabbitmq:3.13-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-service

  configserver:
    image: ghergutmadalin/configserver:latest
    container_name: configserver
    ports:
      - "8071:8071"
    depends_on:
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "apt-get update > /dev/null 2>&1 && apt-get install -y curl > /dev/null 2>&1 && curl --fail --silent localhost:8071/actuator/health/readiness | grep -q UP"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: base-service

  eurekaserver:
    image: ghergutmadalin/eurekaserver:latest
    container_name: eurekaserver
    ports:
      - "8761:8761"
    depends_on:
      configserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: "apt-get update > /dev/null 2>&1 && apt-get install -y curl > /dev/null 2>&1 && curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 1"
#      Nu le schimba =)
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    extends:
      file: common-config.yml
      service: app-service

  gatewayserver:
    image: ghergutmadalin/gatewayserver:latest
    container_name: gatewayserver
    ports:
      - "8072:8072"
    healthcheck:
      test: "apt-get update > /dev/null 2>&1 && apt-get install -y curl > /dev/null 2>&1 && curl --fail --silent localhost:8072/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    depends_on:
      accounts:
        condition: service_healthy
      loans:
        condition: service_healthy
      cards:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: app-service

  accounts:
    image: ghergutmadalin/accounts:latest
    container_name: accounts
    pull_policy: always
    ports:
      - "8080:8080"
    healthcheck:
      test: "apt-get update > /dev/null 2>&1 && apt-get install -y curl > /dev/null 2>&1 && curl --fail --silent http://localhost:8080/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      accountsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: app-service

  loans:
    image: ghergutmadalin/loans:latest
    container_name: loans
    pull_policy: always
    ports:
      - "8090:8090"
    healthcheck:
      test: "apt-get update > /dev/null 2>&1 && apt-get install -y curl > /dev/null 2>&1 && curl --fail --silent http://localhost:8090/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      loansdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: app-service

  cards:
    image: ghergutmadalin/cards:latest
    container_name: cards
    pull_policy: always
    ports:
      - "9000:9000"
    healthcheck:
      test: "apt-get update > /dev/null 2>&1 && apt-get install -y curl > /dev/null 2>&1 && curl --fail --silent http://localhost:9000/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 45s
    depends_on:
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
      cardsdb:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: app-service

  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data /data/loki-ruler && minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - "9001:9000"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    extends:
      file: common-config.yml
      service: network-service

  gateway:
    image: nginx:1.27-alpine
    container_name: loki-gateway
    depends_on:
      - read
      - write
      - backend
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/nginx.conf
        user nginx;
        worker_processes 5;
        error_log /var/log/nginx/error.log;
        pid /var/run/nginx.pid;
        worker_rlimit_nofile 8192;
        events {
          worker_connections 4096;
        }
        http {
          default_type application/octet-stream;
          log_format main '\$$remote_addr - \$$remote_user [\$$time_local] \$$status '
            '"\$$request" \$$body_bytes_sent "\$$http_referer" '
            '"\$$http_user_agent" "\$$http_x_forwarded_for"';
          access_log /var/log/nginx/access.log main;
          sendfile on;
          tcp_nopush on;
          server_names_hash_bucket_size 128;
          upstream read { server read:3100; }
          upstream write { server write:3100; }
          upstream backend { server backend:3100; }
          server {
            listen 3100;
            location = / {
              return 200 'OK';
              auth_basic off;
            }
            location = /api/prom/push { proxy_pass http://write\$$request_uri; }
            location = /api/prom/tail {
              proxy_pass http://read\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }
            location ~ /api/prom/.* { proxy_pass http://read\$$request_uri; }
            location = /loki/api/v1/push { proxy_pass http://write\$$request_uri; }
            location = /loki/api/v1/tail {
              proxy_pass http://read\$$request_uri;
              proxy_set_header Upgrade \$$http_upgrade;
              proxy_set_header Connection "upgrade";
            }
            location ~ /loki/api/.* { proxy_pass http://read\$$request_uri; }
            location ~ /compactor/.* { proxy_pass http://backend\$$request_uri; }
          }
        }
        EOF
        /docker-entrypoint.sh nginx -g "daemon off;"
    ports:
      - "3100:3100"
    extends:
      file: common-config.yml
      service: network-service

  read:
    image: grafana/loki:3.2.0
    container_name: loki-read
    command: "-config.file=/etc/loki/config.yaml -target=read"
    ports:
      - "3101:3100"
      - "7946"
      - "9095"
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    extends:
      file: common-config.yml
      service: network-service

  write:
    image: grafana/loki:3.2.0
    container_name: loki-write
    command: "-config.file=/etc/loki/config.yaml -target=write"
    ports:
      - "3102:3100"
      - "7947:7946"
      - "9096:9095"
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - minio
    extends:
      file: common-config.yml
      service: network-service

  backend:
    image: grafana/loki:3.2.0
    container_name: loki-backend
    command: "-config.file=/etc/loki/config.yaml -target=backend -legacy-read-mode=false"
    ports:
      - "3103:3100"
      - "7948:7946"
    volumes:
      - ../observability/loki/loki-config.yaml:/etc/loki/config.yaml
    depends_on:
      - minio
    extends:
      file: common-config.yml
      service: network-service

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/etc/prometheus/console_libraries
      - --web.console.templates=/etc/prometheus/consoles
      - --web.enable-lifecycle
      - --web.enable-remote-write-receiver
    volumes:
      - ../observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    extends:
      file: common-config.yml
      service: network-service

  tempo:
    image: grafana/tempo:2.6.0
    container_name: tempo
    user: "0:0"
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ../observability/tempo/tempo.yml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    extends:
      file: common-config.yml
      service: network-service

  alloy:
    image: grafana/alloy:v1.4.0
    container_name: alloy
    ports:
      - "12345:12345"
    volumes:
      - ../observability/alloy/config.alloy:/etc/alloy/config.alloy
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
    depends_on:
      - gateway
    extends:
      file: common-config.yml
      service: network-service

  grafana:
    image: grafana/grafana:11.2.2
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ../observability/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - gateway
      - tempo
    extends:
      file: common-config.yml
      service: network-service

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
      KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    volumes:
      - keycloak-data:/opt/keycloak/data
    extends:
      file: common-config.yml
      service: network-service

  rabbit:
    image: rabbitmq:4.0-management
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    extends:
      file: common-config.yml
      service: network-service

  message:
    image: "ghergutmadalin/message:latest"
    container_name: message-ms
    pull_policy: always
    ports:
      - "9010:9010"
    depends_on:
      rabbit:
        condition: service_healthy
    environment:
      SPRING_RABBITMQ_HOST: rabbit
    extends:
      file: common-config.yml
      service: network-service

volumes:
  minio-data:
  prometheus-data:
  grafana-data:
  tempo-data:
  keycloak-data:

networks:
  eazybank:
    name: eazybank
    driver: bridge