{{- if .Values.eurekaserver.enabled }}
# Eureka Server - service discovery and registration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.eurekaserver.service.name }}
  labels:
    app: {{ .Values.eurekaserver.labels.app }}
    {{- if .Values.eurekaserver.labels.tier }}
    tier: {{ .Values.eurekaserver.labels.tier }}
    {{- end }}
spec:
  replicas: {{ .Values.eurekaserver.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.eurekaserver.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.eurekaserver.labels.app }}
        {{- if .Values.eurekaserver.labels.tier }}
        tier: {{ .Values.eurekaserver.labels.tier }}
        {{- end }}
    spec:
      containers:
      - name: eurekaserver
        image: {{ .Values.eurekaserver.image.repository }}:{{ .Values.eurekaserver.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.eurekaserver.containerPort }}
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: eazybank-config
              key: SPRING_PROFILES_ACTIVE
        - name: SPRING_CONFIG_IMPORT
          valueFrom:
            configMapKeyRef:
              name: eazybank-config
              key: SPRING_CONFIG_IMPORT
        resources:
          limits:
            memory: {{ .Values.eurekaserver.resources.limits.memory }}
          requests:
            memory: {{ .Values.eurekaserver.resources.requests.memory }}
            cpu: {{ .Values.eurekaserver.resources.requests.cpu }}
        livenessProbe:
          httpGet:
            path: {{ .Values.eurekaserver.probes.liveness.path }}
            port: {{ .Values.eurekaserver.containerPort }}
          initialDelaySeconds: {{ .Values.eurekaserver.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.eurekaserver.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.eurekaserver.probes.liveness.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.eurekaserver.probes.readiness.path }}
            port: {{ .Values.eurekaserver.containerPort }}
          initialDelaySeconds: {{ .Values.eurekaserver.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.eurekaserver.probes.readiness.periodSeconds }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.eurekaserver.service.name }}
  labels:
    app: {{ .Values.eurekaserver.labels.app }}
spec:
  selector:
    app: {{ .Values.eurekaserver.labels.app }}
  type: {{ .Values.eurekaserver.service.type }}
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.eurekaserver.service.port }}
      targetPort: {{ .Values.eurekaserver.containerPort }}
{{- end }}

