{{- if .Values.grafana.enabled }}
# Grafana - observability dashboards
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    app: grafana
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      {{- if .Values.prometheus.enabled }}
      - name: Prometheus
        type: prometheus
        uid: prometheus
        url: http://prometheus:{{ .Values.prometheus.service.port }}
        access: proxy
        isDefault: true
        editable: true
      {{- end }}
      {{- if .Values.loki.enabled }}
      - name: Loki
        type: loki
        uid: loki
        url: http://loki-gateway:{{ .Values.loki.service.port }}
        access: proxy
        editable: true
        jsonData:
          httpHeaderName1: "X-Scope-OrgID"
          derivedFields:
            - datasourceUid: tempo
              matcherRegex: "\[.+,(.+),.+\]"
              name: TraceID
              url: '${__value.raw}'
        secureJsonData:
          httpHeaderValue1: "tenant1"
      {{- end }}
      {{- if .Values.tempo.enabled }}
      - name: Tempo
        type: tempo
        uid: tempo
        url: http://tempo:3200
        access: proxy
        editable: true
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: {{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            configMapKeyRef:
              name: eazybank-config
              key: GF_SECURITY_ADMIN_USER
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: eazybank-config
              key: GF_SECURITY_ADMIN_PASSWORD
        - name: GF_USERS_ALLOW_SIGN_UP
          valueFrom:
            configMapKeyRef:
              name: eazybank-config
              key: GF_USERS_ALLOW_SIGN_UP
        volumeMounts:
        - name: grafana-data
          mountPath: /var/lib/grafana
        - name: grafana-datasource
          mountPath: /etc/grafana/provisioning/datasources
      volumes:
      - name: grafana-data
        emptyDir: {}
      - name: grafana-datasource
        configMap:
          name: grafana-datasource
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: {{ .Values.grafana.service.type }}
  ports:
    - name: http
      port: {{ .Values.grafana.service.port }}
      targetPort: 3000
{{- end }}

